// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-6bIwdJ2moodJOqExaHPkMmqhOGZNecg',
    appId: '1:500859127094:web:92b068a9f2e54991835f97',
    messagingSenderId: '500859127094',
    projectId: 'expensetracker-c6223',
    authDomain: 'expensetracker-c6223.firebaseapp.com',
    storageBucket: 'expensetracker-c6223.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3n9HgZ4DkURIDaV7v4gmf0G4du_OpqWQ',
    appId: '1:500859127094:android:02baefcb1cad362a835f97',
    messagingSenderId: '500859127094',
    projectId: 'expensetracker-c6223',
    storageBucket: 'expensetracker-c6223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmww6Rxlp5fNgO0BRHLh9a3cfXDDho_d8',
    appId: '1:500859127094:ios:c6a229f25c76a7eb835f97',
    messagingSenderId: '500859127094',
    projectId: 'expensetracker-c6223',
    storageBucket: 'expensetracker-c6223.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmww6Rxlp5fNgO0BRHLh9a3cfXDDho_d8',
    appId: '1:500859127094:ios:c6a229f25c76a7eb835f97',
    messagingSenderId: '500859127094',
    projectId: 'expensetracker-c6223',
    storageBucket: 'expensetracker-c6223.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-6bIwdJ2moodJOqExaHPkMmqhOGZNecg',
    appId: '1:500859127094:web:41c7ad401fa39a69835f97',
    messagingSenderId: '500859127094',
    projectId: 'expensetracker-c6223',
    authDomain: 'expensetracker-c6223.firebaseapp.com',
    storageBucket: 'expensetracker-c6223.appspot.com',
  );
}
